# Puerto del servidor
server.port=8080

# Conexión a MySQL (ajusta usuario/contraseña si hace falta)
spring.datasource.url=jdbc:mysql://localhost:3306/seguro_cliente
spring.datasource.username=root
spring.datasource.password=

# No crear/borrar tablas automáticamente (porque ya las tienes en MySQL)
spring.jpa.hibernate.ddl-auto=none

# Muestra por consola las consultas SQL (útil para aprender)
spring.jpa.show-sql=true