# Puerto del servidor
server.port=8080

# Conexi�n a MySQL (ajusta usuario/contrase�a si hace falta)
spring.datasource.url=jdbc:mysql://localhost:3306/seguro_cliente
spring.datasource.username=root
spring.datasource.password=

# No crear/borrar tablas autom�ticamente (porque ya las tienes en MySQL)
spring.jpa.hibernate.ddl-auto=none

# Muestra por consola las consultas SQL (�til para aprender)
spring.jpa.show-sql=true